"""auth, concerts, pieces, instruments, cases, entries

Revision ID: 4a03644f7c50
Revises: 
Create Date: 2026-08-23 18:15:06.216608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a03644f7c50'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instrument_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('note_range_low', sa.String(length=10), nullable=False),
    sa.Column('note_range_high', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_type_id', sa.Integer(), nullable=False),
    sa.Column('case_number', sa.String(length=20), nullable=False),
    sa.Column('note_range_low', sa.String(length=10), nullable=False),
    sa.Column('note_range_high', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['instrument_type_id'], ['instrument_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_number')
    )
    op.create_table('pieces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concert_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('program_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['concert_id'], ['concerts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('concert_id', 'program_order')
    )
    op.create_table('entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('piece_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=20), nullable=False),
    sa.Column('misc_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['piece_id'], ['pieces.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'piece_id')
    )
    op.create_table('piece_instrument_types',
    sa.Column('piece_id', sa.Integer(), nullable=False),
    sa.Column('instrument_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_type_id'], ['instrument_types.id'], ),
    sa.ForeignKeyConstraint(['piece_id'], ['pieces.id'], ),
    sa.PrimaryKeyConstraint('piece_id', 'instrument_type_id')
    )
    op.create_table('entry_instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('instrument_type_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ),
    sa.ForeignKeyConstraint(['instrument_type_id'], ['instrument_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_id', 'instrument_type_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entry_instruments')
    op.drop_table('piece_instrument_types')
    op.drop_table('entries')
    op.drop_table('pieces')
    op.drop_table('cases')
    op.drop_table('users')
    op.drop_table('instrument_types')
    op.drop_table('concerts')
    # ### end Alembic commands ###
